### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by TMIU** [KuoHaoZeng/AAP#1]
Hi, KuoHaoZeng, Thank you for your amazing work. I want to test your models, but the pretrained model paths are not working now. Can you update the pretrained models? Be deeply grateful！

**Comment by KuoHaoZeng** [comment]
Hi, sorry for that the previous links to the pretrained models are broken.
I have updated the links.

**Comment by TMIU** [comment]
Thank you so much!!
